[package]
name = "test_fn_macro"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[lib]
proc-macro = true

[features]
default = []
tokio_executor = []

[dependencies]
quote = "^1"
proc-macro2 = "^1"
syn = "^1"
